(user_symbol) @variable.user_symbol
(builtin_symbol) @constant.builtin.builtin_symbol
(comment) @comment
(number) @number
(string) @string
(string_char_escape) @string.special.char_escape
(string_char_name_escape) @string.special.char_name_escape
(string_char_name) @string.special.char_name

(parenthesis_begin) @punctuation.bracket.parenthesis.begin
(parenthesis_end) @punctuation.bracket.parenthesis_end.begin

(apply_bracket_begin) @punctuation.bracket.apply.begin
(apply_bracket_end) @punctuation.bracket.apply.end
(list_bracket_begin) @punctuation.bracket.list.begin
(list_bracket_end) @punctuation.bracket.list.end
(part_bracket_begin) @punctuation.bracket.part.begin
(part_bracket_end) @punctuation.bracket.part.end
(association_bracket_begin) @punctuation.bracket.association.begin
(association_bracket_end) @punctuation.bracket.association.end

(string_begin) @punctuation.string.double.begin
(string_end) @punctuation.string.double.end

(compound_expression_operator) @operator.compound_expression

(subscript_operator) @operator.subscript
(pattern_test_operator) @operator.pattern_test
(message_name_operator) @operator.message_name
(apply_at_operator) @operator.apply_at
(composition_operator) @operator.composition
(right_composition_operator) @operator.right_composition
(get_operator) @operator.get
(rule_ascii_operator) @operator.rule_ascii
(rule_delayed_ascii_operator) @operator.rule_delayed_ascii
(increment_operator) @operator.increment
(decrement_operator) @operator.decrement
(pre_increment_operator) @operator.pre_increment
(pre_decrement_operator) @operator.pre_decrement
(overscript_operator) @operator.overscript
(underscript_operator) @operator.underscript
(del_operator) @operator.del
(small_circle_operator) @operator.small_circle
(circle_dot_operator) @operator.circle_dot
(non_commutative_multiply_operator) @operator.non_commutative_multiply
(dot_operator) @operator.dot
(backslash_operator) @operator.backslash
(diamond_operator) @operator.diamond
(wedge_operator) @operator.wedge
(vee_operator) @operator.vee
(circle_times_operator) @operator.circle_times
(center_dot_operator) @operator.center_dot
(times_ast_operator) @operator.times_ast
(times_cross_operator) @operator.times_cross
(star_operator) @operator.star
(vertical_tilde_operator) @operator.vertical_tilde
(coproduct_operator) @operator.coproduct
(circle_plus_operator) @operator.circle_plus
(circle_minus_operator) @operator.circle_minus
(plus_operator) @operator.plus
(minus_operator) @operator.minus
(plus_minus_operator) @operator.plus_minus
(negative_operator) @operator.negative
(positive_operator) @operator.positive
(negative_positive_operator) @operator.negative_positive
(per_operator) @operator.per
(divide_operator) @operator.divide
(divide_box_operator) @operator.divide_box
(map_operator) @operator.map
(map_all_operator) @operator.map_all
(factorial_operator) @operator.factorial
(factorial2_operator) @operator.factorial2
(derivative_operator) @operator.derivative
(sqrt_operator) @operator.sqrt
(power_operator) @operator.power
(apply_atat_operator) @operator.apply_atat
(apply_atatat_operator) @operator.apply_atatat
(alternatives_operator) @operator.alternatives
(string_join_operator) @operator.string_join
(set_operator) @operator.set
(set_delayed_operator) @operator.set_delayed
(up_set_operator) @operator.up_set
(up_set_delayed_operator) @operator.up_set_delayed
(unset_operator) @operator.unset
(tag_set_operator_left) @operator.tag_set.left
(tag_set_operator_right) @operator.tag_set.right
(tag_set_delayed_operator_left) @operator.tag_set_delayed.left
(tag_set_delayed_operator_right) @operator.tag_set_delayed.right
(tag_unset_operator_left) @operator.tag_unset.left
(tag_unset_operator_right) @operator.tag_unset.right

(blank) @tag.blank
(blank_sequence) @tag.blank.sequence
(blank_null_sequence) @tag.blank.sequence.null
